### ISSUE TITLE
I met serveral problems when I read the source code of your batch_train in 3on_distill.py

### ISSUE THREAD

**Issue by linln1** [XYGaoG/NAI#1]
Dear Author:

I would appreciate some advice from you.

Question1 is in line 147-152:
    Is that means what we need to train is only the first layer function f(0) and the classification function lr_attn? But Why ?

Question 2 is in line 61 
    ```for hop in np.arange(1, 2):```
I can't understand that why this place the hop should be 1 or 2 ?
Is that supposed to be  
    ```for hop in np.arange(1, args.num_max_hops - args.ensemble_layers + 1):```

                                Thanks for your open codebase
                                                               Best Wishes

**Comment by XYGaoG** [comment]
Hi, 
Thank you for your question. 
Considering that `np.arange(1,2)` only returns the value 1, line 61 means that the first classifier `$f_{(1)}$` will be updated with the teacher model `lr_att`, and other classifiers will be frozen in its round. 
We find that the online distillation for different students is sensitive to hyper-parameters, so all student classifiers are updated independently as described in Eq. (6). To verify the results in Table 6 of the ablation study, we show the codes and results for the classifier `$f_{(1)}$` and you can easily train other student classifiers by adjusting parameters w.r.t classifiers, including parameters mentioned in your two questions.
Considering the performance gap between `$f_{(1)}$`  and other classifiers on Flickr,  the results with enhanced `$f_{(1)}$`  has worked well and you can run `para_search`  to search the hyper-parameters and check the inference accuracy.

**Comment by linln1** [comment]
Thank you
